services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    networks:
      - net
    volumes:
      - db-data:/var/lib/mysql:rw

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    env_file: .env
    networks:
      - net
    volumes:
      - web-data:/var/www/html:rw

networks:
  net:
    driver: bridge

volumes:
  db-data:
    name: db
    driver: local
    driver_opts:
      type: local
      o: bind
      # device: /home/sounchoi/data/db
      device: /Users/sounchoi/test/volume/db
  
  web-data:
    name: web
    driver: local
    driver_opts:
      type: local
      o: bind
      # device: /home/sounchoi/data/web
      device: /Users/sounchoi/test/volume/web

  

